# Generated by Django 5.0.6 on 2024-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField(auto_now_add=True)),
                ('interaction_type', models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('meeting', 'meeting')], default='email', max_length=100)),
                ('notes', models.CharField(max_length=255)),
                ('follow_up', models.CharField(max_length=255)),
                ('client_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=50)),
                ('biz_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('prospect', 'prospect'), ('lead', 'lead'), ('customer', 'customer')], default='prospect', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('todos', models.TextField(blank=True, max_length=1000, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('client_id', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
