# Generated by Django 5.0.6 on 2024-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='biz_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, choices=[('prospect', 'prospect'), ('lead', 'lead'), ('customer', 'customer')], default='prospect', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
