# Generated by Django 5.0.6 on 2024-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_record_address_alter_record_biz_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
