# Generated by Django 5.0.6 on 2024-06-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_record_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
