# Generated by Django 5.0.6 on 2024-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_record_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deal',
            field=models.CharField(blank=True, choices=[('won', 'won'), ('lost', 'lost'), ('wip', 'wip')], default='wip', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='expected_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
