# Generated by Django 5.0.6 on 2024-07-05 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_interaction_interaction_date_alter_record_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name_plural': 'Todos'},
        ),
        migrations.AddField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(blank=True, choices=[('prospect', 'prospect'), ('lead', 'lead'), ('customer', 'customer'), ('all', 'all')], default='prospect', max_length=50, null=True),
        ),
    ]
